language: node_js

node_js:
  - "7"

branches:
  only:
  - master

env:
  - BROWSERS_SET=ie
  - BROWSERS_SET=edge
  - BROWSERS_SET=safari-current
  - BROWSERS_SET=opera-mobile
  - BROWSERS_SET=yandex
  - BROWSERS_SET=android-current
  - BROWSERS_SET=ios-current
  - BROWSERS_SET=chrome
  - BROWSERS_SET=firefox
  - BROWSERS_SET=opera

before_install:
  - export CC=gcc-6
  - export CXX=g++-6

before_script:
  - npm run instrument

after_script:
  - npm run coverage

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-6
