language: node_js

node_js:
  - "7"

branches:
  only:
  - master

env:
  - BROWSERS_SET=chrome
  - BROWSERS_SET=firefox
  - BROWSERS_SET=opera
  - BROWSERS_SET=ie
  - BROWSERS_SET=android
  - BROWSERS_SET=ios
  - BROWSERS_SET=safari
  - BROWSERS_SET=ie-mobile
  - BROWSERS_SET=edge
  - BROWSERS_SET=opera-mobile
  - BROWSERS_SET=yandex

before_install:
  - export CC=gcc-6
  - export CXX=g++-6

before_script:
  - LOG_LEVEL=INFO node ./node_modules/cross-browser-tests-runner/server.js &

cache:
  directories:
    - node_modules

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-6
